version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: Go@123456
    command: ["redis-server", "--requirepass", "Go@123456"]