// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app-server/internal/infrastructure/config"
	"app-server/internal/infrastructure/database"
	"app-server/internal/infrastructure/server"
	"app-server/internal/interface/api/handler/v1"
	"app-server/internal/persistence/repository/postgres"
	"app-server/internal/usecase/user"
)

// Injectors from wire.go:

// InitializeServer sẽ inject tất cả các dependencies và trả về Server
func InitializeServer(config2 *config.Config) (*server.HTTPServer, error) {
	db, err := database.Connect(config2)
	if err != nil {
		return nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	serviceInterface := user.NewService(userRepository)
	userHandler := v1.NewUserHandler(serviceInterface)
	httpServer := server.NewHTTPServer(config2, userHandler)
	return httpServer, nil
}
