app:
  name: "AppServer"
  port: 8080

database:
  host: "51.79.212.76"
  port: 15432
  name: "postgres"
  user: "postgres"
  password: "kD9gdhQh"
  schema: "demovcs"

jwt:
  secret: "Acb@123456"
  token_expiry: 180 # minutes
