app:
  name: "AppServer"
  port: 8080

database:
  host: "51.79.212.76"
  port: 15432
  name: "vcs"
  user: "postgres"
  password: "kD9gdhQh"
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@gmail.com"
  password: "your-email-password"
jwt:
  secret: "Acb@123456"
  token_expiry: 3600
