name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Thiết lập Go environment
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Tải các dependency
      - name: Get dependencies
        run: go mod download

      # Chạy lệnh build
      - name: Build the Go app
        run: go build -v ./...

      # Thiết lập biến môi trường cho test
      - name: Set environment variables
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
          echo "DB_NAME=app_db" >> $GITHUB_ENV

      # Chạy các bài kiểm thử
      - name: Run tests
        run: go test ./...

      # Push image lên Docker Hub (tùy chọn)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/app-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/app-server:latest
